<div id="main">
    <p>
        <blockquote>
            &#34;Deixe-me ir, preciso andar,<br/>
            Vou por ai, a procurar,<br/>
            Sorrir pra nao chorar<br/>
            &#40;...&#41;<br/>
            E se alguem por mim perguntar,<br/>
            Diga que eu so vou voltar<br/>
            Quando eu me encontrar...&#34;
        </blockquote>
        <span id="author">
            &#40;Candeia&#41;
        </span>
    </p>
</div>
<section id="mosaic">
    <ul>
        <li><img src="content/index/inox-m.jpg" class="mini"><img src="content/index/inox.jpg" class="pic"></li>
        <li><img src="content/index/maroc1-m.jpg" class="mini"><img src="content/index/maroc1.jpg" class="pic"></li>
        <li><img src="content/index/maroc2-m.jpg" class="mini"><img src="content/index/maroc2.jpg" class="pic"></li>
        <li><img src="content/index/oktober-m.jpg" class="mini"><img src="content/index/oktober.jpg" class="pic"></li>
        <li><img src="content/index/torre-m.jpg" class="mini"><img src="content/index/torre.jpg" class="pic"></li>
        <li><img src="content/index/austria-m.jpg" class="mini"><img src="content/index/austria.jpg" class="pic"></li>
    </ul>
</section>
